#!/usr/bin/env bash
# A script to install nginx server on an ubuntu linux distro.

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
